sqlite3:
  uri: "data/test_goi.db"

mysql:
  uri: "xxx:xxx@tcp(127.0.0.1:3306)/test_goi"

redis:
  addr: "127.0.0.1:6379"
  password: "xxxx"
  db: 10

mongodb:
  uri: "mongodb://127.0.0.1:27017"
  username: "xxx"
  password: "xxx"
  database: "test_goi"
